# https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

name: Publish to PyPI and TestPyPI

on: push

permissions:
  contents: read

jobs:
  build-golemcpp-waflib:
    name: Build golemcpp-waflib
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: actions/setup-python@v6
        with:
          python-version: "3.x"
      - name: Build golemcpp-waflib
        run: |
          python -m pip install build
          python -m build
        working-directory: waflib/
      - name: Upload golemcpp-waflib
        uses: actions/upload-artifact@v5
        with:
          name: golemcpp-waflib-dists
          path: waflib/dist/
          
  build-golemcpp:
    name: Build golemcpp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: actions/setup-python@v6
        with:
          python-version: "3.x"
      - name: Build golemcpp
        run: |
          python -m pip install build
          python -m build
      - name: Upload golemcpp
        uses: actions/upload-artifact@v5
        with:
          name: golemcpp-dists
          path: dist/

  pypi-publish-golemcpp-waflib:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
    needs:
      - build-golemcpp-waflib
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
    environment:
      name: pypi
      url: https://pypi.org/p/golemcpp-waflib
    steps:
      - name: Retrieve golemcpp-waflib
        uses: actions/download-artifact@v6
        with:
          name: golemcpp-waflib-dists
          path: waflib/dist/
      - name: Publish golemcpp-waflib to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: waflib/dist/

  testpypi-publish-golemcpp-waflib:
    runs-on: ubuntu-latest
    needs:
      - build-golemcpp-waflib
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
    environment:
      name: testpypi
      url: https://test.pypi.org/p/golemcpp-waflib
    steps:
      - name: Retrieve golemcpp-waflib
        uses: actions/download-artifact@v6
        with:
          name: golemcpp-waflib-dists
          path: waflib/dist/
      - name: Publish golemcpp-waflib to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: waflib/dist/
          repository-url: https://test.pypi.org/legacy/

  pypi-publish-golemcpp:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
    needs:
      - pypi-publish-golemcpp-waflib
      - build-golemcpp
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
    environment:
      name: pypi
      url: https://pypi.org/p/golemcpp
    steps:
      - name: Retrieve golemcpp
        uses: actions/download-artifact@v6
        with:
          name: golemcpp-dists
          path: dist/
      - name: Publish golemcpp to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/

  testpypi-publish-golemcpp:
    runs-on: ubuntu-latest
    needs:
      - testpypi-publish-golemcpp-waflib
      - build-golemcpp
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
    environment:
      name: testpypi
      url: https://test.pypi.org/p/golemcpp
    steps:
      - name: Retrieve golemcpp
        uses: actions/download-artifact@v6
        with:
          name: golemcpp-dists
          path: dist/
      - name: Publish golemcpp to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
          repository-url: https://test.pypi.org/legacy/
